import Head from "next/head";
import CardList from "@/components/cardList";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Next.js BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CardList postList={posts} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://dummyjson.com/posts");
  const posts = await res.json();

  return {
    props: {
      posts: posts.posts,
    },
  };
}
