"use client";
import Image from "next/image";
import { Bubblegum_Sans, Inter } from "@next/font/google";
import styles from "./page.module.css";
import { useState } from "react";
import ConfettiExplosion from "react-confetti-explosion";
import Head from "@/app/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isExploding, setIsExploding] = useState(150);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.boom}>
          {isExploding && (
            <ConfettiExplosion
              setIsExploding={setIsExploding}
              width={1500}
              height={800}
              colors={["#66FF00", "#fffff", "#ff0000"]}
              particleSize={10}
              duration={3500}
              force={0.5}
            />
          )}
        </div>
        <input
          className={styles.btn}
          type="button"
          value="💣"
          //onClick={(e) => setIsExploding(true)}
        ></input>
        <h1 className={styles.text}>CONGRATULAZIONI!</h1>
      </main>
    </>
  );
}
