const players = [
  {
    id: 1,
    title: "Alisson Becker",
    role: "Goalkeeper",
    ability: "1",
    weakfoot: "4",
    nationality: "Brasil",
    price: 60000,
    rating: 89,
    quantity: 35,
    league: "Premier League",
    runstyle: "none",
    image: "https://cdn.futbin.com/content/fifa23/img/players/212831.png?v=23",
  },
  {
    id: 2,
    title: "Thibaut Courtois",
    role: "Goalkeeper",
    ability: "1",
    weakfoot: "3",
    nationality: "Belgium",
    price: 80000,
    rating: 90,
    quantity: 50,
    league: "Liga",
    runstyle: "none",
    image: "https://cdn.futbin.com/content/fifa23/img/players/192119.png?v=23",
  },
  {
    id: 3,
    title: " Virgil Van Dijk",
    role: "Defender",
    ability: "3",
    weakfoot: "3",
    nationality: "Holland",
    price: 200000,
    rating: 90,
    quantity: 60,
    league: "Premier League",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/203376.png?v=23",
  },
  {
    id: 4,
    title: "Antonio Rudiger",
    role: "Defender",
    ability: "3",
    weakfoot: "2",
    nationality: "Germany",
    price: 100000,
    rating: 87,
    quantity: 80,
    league: "Liga",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/205452.png?v=23",
  },
  {
    id: 5,
    title: "Sergio Ramos",
    role: "Defender",
    ability: "3",
    weakfoot: "4",
    nationality: "Spain",
    price: 20000,
    rating: 84,
    quantity: 74,
    league: "Ligue 1",
    runstyle: "controlled",
    image: "https://cdn.futbin.com/content/fifa23/img/players/155862.png?v=23",
  },
  {
    id: 6,
    title: "Marquinhos",
    role: "Defender",
    ability: "3",
    weakfoot: "4",
    nationality: "Brasil",
    price: 40000,
    rating: 88,
    quantity: 83,
    league: "Ligue 1",
    runstyle: "controlled",
    image: "https://cdn.futbin.com/content/fifa23/img/players/207865.png?v=23",
  },
  {
    id: 7,
    title: "Luka Modric",
    role: "Midfielder",
    ability: "4",
    weakfoot: "4",
    nationality: "Croatia",
    price: 25000,
    rating: 88,
    quantity: 54,
    league: "Liga",
    runstyle: "explosive",
    image: "https://cdn.futbin.com/content/fifa23/img/players/177003.png?v=23",
  },
  {
    id: 8,
    title: "Kevin De Bruyne",
    role: "Midfielder",
    ability: "4",
    weakfoot: "5",
    nationality: "Belgium",
    price: 110000,
    rating: 91,
    quantity: 32,
    league: "Premier League",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/192985.png?v=23",
  },
  {
    id: 9,
    title: "Pedri",
    role: "Midfielder",
    ability: "4",
    weakfoot: "4",
    nationality: "Spain",
    price: 20000,
    rating: 85,
    quantity: 44,
    league: "Liga",
    runstyle: "explosive",
    image: "https://cdn.futbin.com/content/fifa23/img/players/251854.png?v=23",
  },
  {
    id: 10,
    title: "Marco Verratti",
    role: "Midfielder",
    ability: "4",
    weakfoot: "4",
    nationality: "Italy",
    price: 15000,
    rating: 87,
    quantity: 35,
    league: "Ligue 1",
    runstyle: "explosive",
    image: "https://cdn.futbin.com/content/fifa23/img/players/199556.png?v=23",
  },
  {
    id: 11,
    title: "Erling Haaland",
    role: "Forward",
    ability: "3",
    weakfoot: "3",
    nationality: "Norway",
    price: 150000,
    rating: 88,
    quantity: 23,
    league: "Premier League",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/239085.png?v=23",
  },
  {
    id: 12,
    title: "Kylian Mbappe",
    role: "Forward",
    ability: "5",
    weakfoot: "4",
    nationality: "France",
    price: 120000,
    rating: 91,
    quantity: 15,
    league: "Ligue 1",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/231747.png?v=23",
  },
  {
    id: 13,
    title: "Lionel Messi",
    role: "Forward",
    ability: "4",
    weakfoot: "4",
    nationality: "Argentina",
    price: 100000,
    rating: 90,
    quantity: 51,
    league: "Ligue 1",
    runstyle: "controlled",
    image: "https://cdn.futbin.com/content/fifa23/img/players/158023.png?v=23",
  },
  {
    id: 14,
    title: "Neymar Jr",
    role: "Forward",
    ability: "5",
    weakfoot: "5",
    nationality: "Brasil",
    price: 90000,
    rating: 89,
    quantity: 64,
    league: "Ligue 1",
    runstyle: "controlled",
    image: "https://cdn.futbin.com/content/fifa23/img/players/190871.png?v=23",
  },
  {
    id: 15,
    title: "Cristiano Ronaldo",
    role: "Forward",
    ability: "5",
    weakfoot: "4",
    nationality: "Portugal",
    price: 120000,
    rating: 90,
    quantity: 50,
    league: "Premier League",
    runstyle: "lenghty",
    image: "https://cdn.futbin.com/content/fifa23/img/players/20801.png?v=23",
  },
];

export default players;
